name: Submit to Addons.mozilla.org

on: workflow_dispatch

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          runtime: node@lts

      - name: Zip extensions
        run: pnpm zip:firefox

      - name: Submit to stores
        run: |
          pnpm wxt submit \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
